name: developer merge
on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-format-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker (Install Docker)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64

      - name: Install Docker engine
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t pr-image -f Dockerfile.dev .

      - name: Run Docker Image lint and format
        run: docker run --rm pr-image npm run lint && npm run leoispretty
